### ISSUE TITLE
ThingSpeak

### ISSUE THREAD

**Issue by rudderz243** [SmartHydro/SmartHydro#7]
@rece212 to comment on this. ThingSpeak was mentioned in the previous meeting 14/09/2023.

Further discussion is required before implementation can begin.

**Comment by rece212** [comment]
> @rece212 to comment on this. ThingSpeak was mentioned in the previous meeting 14/09/2023.
> 
> Further discussion is required before implementation can begin.

No need ,will be done by firebase instead
